import { getAllPosts } from '@/lib/notionAPI'
import Head from 'next/head'

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return (
    props: {
      allPosts,
    }.
    revalidata: 60,
  );
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

